name: OZIP Decrypter by TechyMinati... 

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  FIRMWARE_LINK: https://download.c.realme.com/flash/Rollbackpack/realme_narzo%2020/RMX2191_11_OTA_0190_all_nksxIPHHdisT.ozip #edit link here...
  FIRMWARE_NAME: RMX2191_11_OTA_0190_all_nksxIPHHdisT.ozip  #edit file name here, you can find the name of file from link itself...
  FINAL_ZIP_NAME: THE_NAME_OF_ZIP_YOU_WANT.zip #This will be the name of final zip which will be uploaded. You can leave it unchanged.
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Downloading Ozip Now
         run: |
            sudo -E apt-get -qq update
            sudo apt install aria2
            aria2c $FIRMWARE_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo apt-get install python-pip
             sudo -H pip install --upgrade pip
             sudo -H pip install setuptools wheel docopt pycryptodome
             wget https://raw.githubusercontent.com/techyminati/oppo_ozip_decrypt/master/ozipdecrypt.py
             sudo python ozipdecrypt.py $FIRMWARE_NAME
             pwd && ls 

       - name: ziping decrypted file
         run: |
             cd out
             sudo zip -r $FINAL_ZIP_NAME * #Don't edit it. Don't edit it and Don't edit this line.
             pwd && ls

       - name: Upload Decrypted zip
         run: |
             pwd && ls
             cd out
             curl https://bashupload.com/ -T $FINAL_ZIP_NAME #file will be uploaded to bashupload, so mirror it if you are decrypting for community uses.
